### ISSUE TITLE
User Dashboard Data Aggregation

### ISSUE THREAD

**Issue by edwintran235** [edwintran235/326-team9#40]
**Description**: 
Creates a single dashboard API that groups multiple types of user-specific data into a single response. This will include a greeting based on the time of day, user-specific announcements/reminders, and recent activity. This is just as a welcome for the user. It will show up the first time the user logs in for the day. There will be an option to not show it for the rest of the day that the user can click.

**Points**: 5

**Category**: Large

**Assigned to**: Edwin Tran

**Comment by megraves** [comment]
This is really great for UX. Personable messages are awesome! Looking forward to seeing how it turns out.

**Comment by laurensheaa** [comment]
This is a nice feature to have and I think it will make it much more personal and catered to the user.

**Comment by shubhami77** [comment]
This is a great idea for making the user feel like they are valued, and over all leading to an interactive experience.

**Comment by krishsharma1008** [comment]
Should the recent activity section include actions taken in the current session or only past logins?
