### ISSUE TITLE
Trash Functionality

### ISSUE THREAD

**Issue by ssim31** [edwintran235/326-team9#41]
**Description:** 

This feature will allow users to delete job applications by dragging them to the trash button. Instead of permanently deleting the application, it will be flagged as deleted in the database, and the user can access deleted applications under the profile page.

Applications will remain in the profile page for thirty days and then be permanently deleted... Unless they are restored or permanently deleted by the user. (1 point)

This feature will be integrated with the front-end's drag-and-drop trash icon functionality, removing applications from the homepage once deleted. (2 points)

Routes will be made for the soft-delete functionality, fetching all deleted applications (to show under the profile page), and for the permanently delete functionality. (2 points)

**Owner:** Sofia Simonoff

**Comment by edwintran235** [comment]
How will the user be able to access the trash later? Will clicking the trash button do anything?

**Comment by megraves** [comment]
The trash button is currently a little small. I wonder if we can make a drop box such that when an application is dragged, it appears and the users can drop it there if they want to delete the application. How do you envision this?

**Comment by ShahabKiyani** [comment]
looks good! let me know when you plan on implementing this as if it goes on the profile page we can work together on layout design!

**Comment by laurensheaa** [comment]
I rlly like this feature and I like the 30 days idea. Is the deleted applications gonna be a page itself that is accessed from the profile or just a section or feature on the profile page?

**Comment by ssim31** [comment]
After reviewing the team’s feedback, I am confirming that I will be implementing this feature. The trash functionality will flag applications as deleted in the database, and users will be able to access their recently deleted applications. I will work with Shahab to decide how the deleted applications will be accessed, either by clicking the delete button or through the profile page. I will also make the delete button larger, as suggested, to improve visibility and make it easier for users to interact with. Currently, dragging applications over the delete button is how the user is able to delete them.

**Comment by krishsharma1008** [comment]
Will users receive a confirmation prompt before an application is flagged as deleted?

**Comment by ssim31** [comment]
Implemented the trash functionality feature.
