### ISSUE TITLE
Interview Notes Storage and Retrieval

### ISSUE THREAD

**Issue by ssim31** [edwintran235/326-team9#42]
**Description:** This feature allows users to save and view notes about their job interviews, directly linked to each application. Users can store details such as interview dates, formats (e.g., phone call, on-site), and questions asked during the interview.

- Users can add, edit, and view notes for each job application.
- Notes will be stored in the database alongside the application details for easy retrieval.
- The back-end will support front-end forms and views by providing routes to create, update, and fetch notes.

Point Value: 5 points
Size Category: Medium
Owner: Sofia Simonoff

**Comment by edwintran235** [comment]
Is there any way to somehow retrieve some tips that may already be online?

**Comment by megraves** [comment]
Will there be buttons to save/edit? I assume there will be a box where users can enter notes, then when they click "save" the information in the box is updated and stays even if the page reloads. This will be a nice feature!

**Comment by ShahabKiyani** [comment]
if a user wants multiple notes for the same application will they all be stored in one long paragraph or will they be able to create multiple seperate notes?

**Comment by laurensheaa** [comment]
I really like this feature! Adding on to what Shahab said, will the notes be displayed on the page or will they be accessed by clicking on a notes button or something else?

**Comment by ssim31** [comment]
After reviewing the team's feedback, I am confirming that I will be implementing this feature. The notes will be stored below the application information for easy retrieval, and users will have the option to add, edit, and view interview notes. Users will be able to input separate notes for each interview session, with options for interview date and format.

**Comment by shubhami77** [comment]
Great idea, and yeah we can work together to integrate it with the interview tips page so the user can be suggested tips based on their interviews.
