### ISSUE TITLE
Restore from Trash

### ISSUE THREAD

**Issue by ssim31** [edwintran235/326-team9#43]
**Description:** 

This feature allows users to restore deleted job applications from the trash. They can view deleted applications through their profile page. By restoring an application, it will reappear in the main list as an active application.

A route will be created to update the status of an application to isDeleted: false and dateDeleted: null. (1 point)

This feature will be implemented so that a user can click a "Restore" and the application will be moved from the profile page to the homepage (2 points). 

**Owner:** Sofia Simonoff

**Comment by edwintran235** [comment]
Which section will the restored application go to?

**Comment by ShahabKiyani** [comment]
looks good to me!

**Comment by laurensheaa** [comment]
I think this is an important feature to have especially with the drag and drop features we have since accidentally dropping in the trash could easily happen

**Comment by shubhami77** [comment]
This is a great idea to improve the user experience.

**Comment by ssim31** [comment]
After reviewing the team's feedback, I am confirming that this feature will be implemented. I will be assigned to it. I will collaborate with @megraves on retrieval from the database, and in response to @edwintran235's question, I will implement the feature so that the user can decide which stage the application should be returned to after restoration, or if they want to default to the last stage before deletion.

**Comment by ssim31** [comment]
Restore from trash feature implemented.
