### ISSUE TITLE
Application Sorting

### ISSUE THREAD

**Issue by edwintran235** [edwintran235/326-team9#44]
**Description**:
A way to sort the applications in different ways, such as day applied and alphabetical.

**Points**: 3

**Size**: Medium

**Assigned to**: Edwin Tran

**Comment by megraves** [comment]
Will you be able to sort the applications by dragging and dropping? Or do you plan on doing it in a different way?

**Comment by ssim31** [comment]
This sounds like a useful feature. You could also give users the option to customize a default option when logging in.

**Comment by ShahabKiyani** [comment]
how will this feature interact with the ui? I am aware we are using 'boxes' to display the applications in different sections, so how will this alter that? Might be good to communicate with those who worked on the ui for that page on this!

**Comment by shubhami77** [comment]
I am working on prioritizing applications based on user preferences. It seems like your sorting is based on the features of the application, we could collaborate on this to implement both seamlessly.

**Comment by laurensheaa** [comment]
Im gonna work on sorting the deadlines and reminders so we should collaborate on how to implement sorting algorithms

**Comment by krishsharma1008** [comment]
Will the sorting options be accessible through a dropdown menu or another UI element?

**Comment by edwintran235** [comment]
Final Comment: This feature will be included and completed by Edwin. There will be a drop down box with options on how to sort the applications. The sorting algorithm will be applied to each of the 4 boxes, sorting them separately. Each application in the section boxes will be reorganized to appear sorted. Shubham will also be working on something similar, so in the drop down box, his option for sorting will be included. Once the applications have been sorted, the user will not be able to reorganize them by dragging. If the application is dragged to another status box, it will automatically be sorted in the way that was chosen.
