### ISSUE TITLE
Drag and Drop Status Update

### ISSUE THREAD

**Issue by edwintran235** [edwintran235/326-team9#45]
**Description**: 
When the user grabs an application and drags it to a new category, it will update the status of the application

**Points**: 2

**Size**: Medium

**Assigned to**: Edwin Tran

**Comment by megraves** [comment]
Will you need a specific update function in the backend so that the database is updated as well?

**Comment by ssim31** [comment]
This is important to make sure the information is accurate when viewing the application information.

**Comment by ShahabKiyani** [comment]
Looks good! I second megraves comment above^

**Comment by laurensheaa** [comment]
Definitely a necessary feature

**Comment by shubhami77** [comment]
Looks great, this is an important feature for the user to be able to track their progression.

**Comment by krishsharma1008** [comment]
Will there be a visual confirmation or animation when the application is successfully moved to a new category?

**Comment by edwintran235** [comment]
Final Comment: This feature will be included and completed by Edwin. When a user drags an application to a different status box and releases it, the status of the application will be updated on the backend. To confirm the drop, there will be a small animation played.
