### ISSUE TITLE
Resume/Cover letter File uploads, backend connection

### ISSUE THREAD

**Issue by ShahabKiyani** [edwintran235/326-team9#47]
On the profile page, users can upload a resume or cover letter as a way to store it, so we need to connect this with the backend to ensure the data persists, allowing users to upload a resume/cover letter and retrieve them. This is so their important documents are stored in an easy to access area so that if they need it for an application, they can retrieve it from their homepage.
Point Value: 6 
Size Category: Large 
Owner: Mohammad Kiyani

**Comment by edwintran235** [comment]
Will you implement a drag and drop box to add the file, or just a button that opens their file explorer?

**Comment by ssim31** [comment]
This is a very useful feature. Are you planning to include options to delete or update files as well?

**Comment by ShahabKiyani** [comment]
> Will you implement a drag and drop box to add the file, or just a button that opens their file explorer?

most likely a button that users can click which will prompt their file page to open

**Comment by ShahabKiyani** [comment]
> This is a very useful feature. Are you planning to include options to delete or update files as well?

users can overwrite their previous inputs by submitting a new one, and I will work on implementing a delete option as well

**Comment by laurensheaa** [comment]
Will this interact with each application so that users can quickly attach the resume and cover letter they used for each application

**Comment by ShahabKiyani** [comment]
After reviewing the team’s feedback, I am confirming that I will be implementing this feature. The cover letter/resume will be stored in the profile page by storing a file path to the file, ensuring a seamless storing process that can translate to other databases incase of future migration. Users will be able to overwrite previous uploads incase they change their documents with updates so that it is reflected in the application. I will use a button prompt rather than drag and drop.

**Comment by ShahabKiyani** [comment]
This feature was modified slightly to work better with the application:
The feature is now functions as an extension of each application, allowing users to attach a resume to each application they submit, so that they can see in the future which resumes they used to apply to each role. This feature interacts with the applications model to handle applicationId, and routes files storage to a folder, storing file paths in the database. This is the final confirmation message for this feature which is now completed.
