### ISSUE TITLE
Name Input on profile page backend connection

### ISSUE THREAD

**Issue by ShahabKiyani** [edwintran235/326-team9#48]
On the profile page, users can input their name so that it will associate those login credentials with your name, allowing your name to appear every time you open the homepage creating a more personal experience. This involves storing the name inputted and then retrieving it every time the homepage is opened for display 
Point Value: 2 
Size Category: Medium 
Assigned to: Mohammad Kiyani

**Comment by edwintran235** [comment]
Will your name being displayed on the homepage be a button that leads anywhere or just to display your name?

**Comment by megraves** [comment]
Once they input their name for the first time, will they be able to edit it or change it?

**Comment by ssim31** [comment]
What happens if a user doesn’t input a name? Will a placeholder be displayed instead... their username or another message?

**Comment by ShahabKiyani** [comment]
> What happens if a user doesn’t input a name? Will a placeholder be displayed instead... their username or another message?

good point! I might try and integrate this into the login page so it is ready to go, and have an edit button on homepage

**Comment by laurensheaa** [comment]
Is this gonna persist across all pages or just the homepage? If it is on the other pages too, maybe it can also be a button like edwin said and take u back to the homepage

**Comment by ShahabKiyani** [comment]
this feature will be closed as it does not seem relevant to the core functions of the application, thus it will be closed.
