### ISSUE TITLE
Create Express.js app for server and routing

### ISSUE THREAD

**Issue by megraves** [edwintran235/326-team9#50]
Create an express app:

- App will handle HTTP requests
- Allows for route management
- have the app connect to our DB
- host locally?

Point Value: 1
Task Size: small
Assigned to: Macy Graves

**Comment by ssim31** [comment]
This is an important feature, I think it's important to start with mapping out the initial routes first and then add more detailed logic later... also need to figure out with routes need to be protected.

**Comment by ShahabKiyani** [comment]
I think designing file structure as well for the backend is a good way to keep everyone else organized, and it can be an extra feature point for you to implement!

**Comment by krishsharma1008** [comment]
Are there any middleware requirements (e.g., for authentication or logging)?

**Comment by megraves** [comment]
### **Final Comment**
**Description**: I will create a server that will run locally using an Express.js app. This will all be included in the ./backend directory. The server will require Node.js to run. This will also be used to connect to our SQLite database using the Sequelize ORM. Most of this code will appear on the index.js file. The README within this directory will have detailed instructions on how to start the server using npm. A .gitignore file will also be present so that we do not commit the node_modules file. The express app will manage our routes and http requests. I plan to use middleware functions to make this possible as described [here](https://expressjs.com/en/guide/using-middleware.html).
**Point Value**: 2
**Task Size**: Medium
**Assigned to**: Macy Graves
