### ISSUE TITLE
Websocket Implementation

### ISSUE THREAD

**Issue by megraves** [edwintran235/326-team9#51]
Enhance client-server communication using a socket over a TCP protocol connection. Allows for swift two-way communication between the client and server. I plan to use the WebSocket API or Socket.io API.

Point Value: 4
Task size: Large
Assigned to: Macy Graves

**Comment by edwintran235** [comment]
How will you decided between WebSocket and Socket.io?

**Comment by ssim31** [comment]
This will be very useful for real-time updates and making our app feel responsive.

**Comment by ShahabKiyani** [comment]
looks good! I think giving us a demo on your implementation will be good as well so we are all familiar with the core functionality of how this works!

**Comment by laurensheaa** [comment]
I think this is gonna really help to make the interactions smooth and easy for users to work with the app

**Comment by shubhami77** [comment]
This is a great implementation for user convenience and for an overall streamlined experience.

**Comment by megraves** [comment]
### **Final Comment**
**Description**: To enhance client-server communication using a socket over a TCP protocol connection, I plan to research and implement sockets using the WebSocket API. Though I have not worked thoroughly with WebSocket before, it was mentioned in class and I want to learn more. This will allows for swift two-way communication between the client and server for overall convenience and a streamlined user experience.

**Point Value**: 4
**Task Size**: Large
**Assigned to**: Macy Graves
