### ISSUE TITLE
SQLite Connection using express

### ISSUE THREAD

**Issue by megraves** [edwintran235/326-team9#52]
Create a new SQLite relational database

- initialize a new database
- create a new tables to represent entities
- create functions to query data (CRUD)
- Use together with Node.js and Express.js
- Emphasis on asynchronous calls

Point Value: 5
Task size: Large
Assigned to: Macy Graves

**Comment by edwintran235** [comment]
Do you already know what the entries of the table will be?

**Comment by ssim31** [comment]
Another important feature! I think documenting the routes would be helpful.

**Comment by ShahabKiyani** [comment]
we will definitely have to collaborate on schemas! seems like an interactive aspect of this project!

**Comment by shubhami77** [comment]
You could also think about how the data will be stored when the page refreshes, and what kind of data you want a user to see, versus what data should be private.

**Comment by laurensheaa** [comment]
Is this replacing the indexedDB implementation?

**Comment by megraves** [comment]
### **Final Comment**
**Description**: I will use the newest SQLite API which is version 3 paired with the latest Sequelize ORM API which is version 7. This will be implemented to replace the IndexedDB implementation. The database will be opened using the Express.js app. We will decide on the relational schema as a group. Then when this is implemented, then all group members will have the ability to make their own CRUD functions that will be useful for their own features.

**Point Value**: 5
**Task Size**: Large
**Assigned to**: Macy Graves

Current Relational Schema: 
![75494350127__EAF75C16-0B51-4638-8876-649123CD46C2](https://github.com/user-attachments/assets/1f1118ed-151a-4c23-9587-2478e322309d)
