### ISSUE TITLE
Storing new applications

### ISSUE THREAD

**Issue by laurensheaa** [edwintran235/326-team9#53]
When a new job is added to the tracker, it is stored on the homepage and stays when the page is refreshed. Each time the page is refreshed or accessed, the job will be fetched from the database in local storage and restored on the homepage in its proper status column. 
Point Value: 3 points
Size Category: Medium
Owner: Lauren Shea

**Comment by ssim31** [comment]
This is a key feature. Will it require specific middleware for error handling or validation?

**Comment by ShahabKiyani** [comment]
is there a way to work around a page refresh every time, as in, will the refresh be visible to the end user? if theres a way we can avoid this for quality of life sake that would be great!

**Comment by edwintran235** [comment]
Since I might be working on the sorting of applications, is there any way we can work together so that the added application will get sorted right as it gets added?

**Comment by shubhami77** [comment]
Is this for completed applications only, or for any application the user is interested in?

**Comment by megraves** [comment]
This is super important. It will include interacting with the DB. Let me know if you have any questions. We can talk about schemas and CRUD functions for getting applications.

**Comment by laurensheaa** [comment]
After reviewing my teams feedback, completed applications will be saved and stored in the database when the user submits a new application using the 'add' button. Upon submitting the application, all of the information will be stored in the database and will be stored so that every time the user logs in or refreshes the page, all of the application information will be shown on the page.
