### ISSUE TITLE
Reminder Sorting and Priority

### ISSUE THREAD

**Issue by laurensheaa** [edwintran235/326-team9#54]
Users can add upcoming deadlines and reminders that are displayed on the homepage. These reminders will be sorted based on soonest deadline. There will be a function to check off the reminder once its been completed. Reminders that have not been checked off and have a deadline that has passed will have some sort of alert (displayed in red, message underneath, etc.. ?) to show that the deadline is passed and not been completed.
Point Value: 6
Size Category: Large
Owner: Lauren Shea

**Comment by ssim31** [comment]
This will definitely improve user experience. I would coordinate with Edwin on issue #40 for upcoming deadlines.

**Comment by edwintran235** [comment]
Will you include any other way to sort it besides due date?

**Comment by shubhami77** [comment]
Will there be a dedicated section in the homepage where the user can see it right away? If so you should think about the placement as it might help with user experience.

**Comment by krishsharma1008** [comment]
Will there be customization options for alert styles (e.g., color, text, icons)?

**Comment by megraves** [comment]
This will require a table in the database. I can make this happen. We can talk about how you want to get the upcoming dates with a crud function.

**Comment by laurensheaa** [comment]
FINAL COMMENT
After reviewing the feedback, I will implement this feature so that reminders are sorted by soonest deadline. The information will be stored in a table in the database and will require functions to get soonest reminders as well as getting reminders sorted by company name.
