### ISSUE TITLE
Upcoming Deadlines attached to job applications

### ISSUE THREAD

**Issue by laurensheaa** [edwintran235/326-team9#55]
When the user clicks on a certain job to see the details of the application, they will have a similar upcoming deadlines column that is specific to that application. Through the backend, any reminder that is associated with that application will be shown in that applications page.
Point Value: 2
Size Category: Medium
Owner: Lauren Shea

**Comment by ssim31** [comment]
This is a great idea for helping users stay organized. If a user makes any CRUD operations to deadlines on the application page then there will need to be backend routes to update and display the correct information when the user views the individual application.

**Comment by edwintran235** [comment]
Going off of Shahab's comment, I think replacing the reminders side bar with the application's deadlines might be something to look into doing!

**Comment by shubhami77** [comment]
Would it be possible to send notification reminders to the user, so that they are reminded even when not looking at the applications page.

**Comment by krishsharma1008** [comment]
Should the reminders column display overdue alerts or completed reminders for better tracking?

**Comment by megraves** [comment]
This is great! I think this is a very helpful tool for our user's experience.

**Comment by laurensheaa** [comment]
FINAL COMMENT
After reviewing the feedback, I will have the upcoming reminders as a sidebar that persists across the homepage to each application page. The reminders on the application page will only be reminders that are tagged for that specific application. When a user inputs a new reminder, they can choose an application to tag the reminder with so that those reminders show up on the specific application page.
