### ISSUE TITLE
Prioritize Applications

### ISSUE THREAD

**Issue by shubhami77** [edwintran235/326-team9#56]
This feature helps users mark and focus on their most desired job applications. Users can "star" or "flag" certain applications, moving them to a priority position or list. This will help them focus their time and energy on the most important applications.
Point Value: 3
Size Category: Medium
Assigned To: Shubham Inavolu

**Comment by edwintran235** [comment]
I'm working on something similar, so if you want to take this one, I can totally do another idea

**Comment by ssim31** [comment]
You might want to consider limiting how many applications can be marked as a priority so ensure that only the top options are being focused on... I think these prioritized applications should remain at the top, regardless of the sorting that is being implemented for Issue #44... maybe that can be for the other applications?

**Comment by laurensheaa** [comment]
Is there gonna be a page or something that users can click on to see all their starred applications in one place? Or will starring the application only affect its position on the homepage?

**Comment by krishsharma1008** [comment]
Should users receive reminders or notifications for their starred applications?

**Comment by megraves** [comment]
It might be nice to have a boolean function that checks if an application "is starred". Then you can easily find those applications and list those first.

**Comment by shubhami77** [comment]
In conclusion after taking the team's feedback into consideration, I would like to confirm that this feature will be implemented and I will be responsible for it. I will be collaborating with @megraves on retrieving data from the database, and @edwintran235 to implement this feature as part of sorting applications.
