### ISSUE TITLE
Tips Page

### ISSUE THREAD

**Issue by shubhami77** [edwintran235/326-team9#57]
A page dedicated to tips posted by alumni, job recruiters, and other experts to allow the user to gain information about how to better improve their resumes, prepare for interviews, and other useful information. This feature allows the user to learn and better prepare themselves for possible behavioral and technical interviews.
Point Value: 5
Size Category: Large
Assigned To: Shubham Inavolu

**Comment by ShahabKiyani** [comment]
What aspects of this will require the backend?

**Comment by edwintran235** [comment]
Do we have the features for this page? #42 may be similar to this one, so maybe you can collaborate together

**Comment by ssim31** [comment]
I think this is a good feature to have so that the user can reference various resume and interview tips throughout the process.

**Comment by laurensheaa** [comment]
So is there gonna be a way for users to input tips to the page? How are the tips going to be posted?

**Comment by krishsharma1008** [comment]
Should users be able to like, bookmark, or comment on tips for engagement?

**Comment by megraves** [comment]
I think this is great. It can populate the page for all users to see and learn from.

**Comment by shubhami77** [comment]
In conclusion, after taking the teams feedback into consideration I would like to confirm that this feature will be implemented, and I will be responsible for it. I will be collaborating with @ssim31 on implementing a link leading to the tips page for the respective stage of the application processes the user is currently on.
