### ISSUE TITLE
 Login and Signup Functionality

### ISSUE THREAD

**Issue by krishsharma1008** [edwintran235/326-team9#58]
Task 1: Login and Signup Functionality
Description:
A login and signup feature that allows users to create accounts and securely store their credentials. The system uses IndexedDB as a lightweight backend for storing user emails and hashed passwords, ensuring secure and persistent data storage directly in the browser. On signup, the backend validates unique emails and encrypts passwords before storage. During login, user input is validated against the stored data, and successful authentication redirects users to the homepage.

Point Value: 3
Size Category: Medium
Assigned To: Krish Sharma

**Comment by edwintran235** [comment]
How will you have the signup page show up?

**Comment by ssim31** [comment]
will the system use indexedDB or will it use one of these: ExpressJS, SQLite, and Sequelize?

**Comment by laurensheaa** [comment]
What will it look like when a user creates an account? Does it also bring them to the homepage or will it prompt them to fill out more information for the profile

**Comment by shubhami77** [comment]
What happens upon unsuccessful authentication? Will the user be given a certain amount of tries to login, or will it just keep asking them to try again?

**Comment by ShahabKiyani** [comment]
looks good!

**Comment by megraves** [comment]
Milestone 3 requires SQLite, which I am implementing. We can talk about what information you would like to store for each user.

**Comment by krishsharma1008** [comment]
Here's how the updated plan addresses your questions:

The signup page will appear as a dedicated route accessible from the login page with clear navigation.
For now, we'll use IndexedDB to meet the task requirements, but we can discuss integrating SQLite for consistency with Milestone 3, as @megraves mentioned.
After account creation, users will be redirected to the homepage but can be prompted to complete their profile with additional information.
On unsuccessful login attempts, an error message will guide users to retry, with optional account recovery links after multiple failed attempts.
