### ISSUE TITLE
User Authentication and Session Management

### ISSUE THREAD

**Issue by krishsharma1008** [edwintran235/326-team9#59]
Implement a backend system using Express.js to handle user authentication securely. Features include:

Storing hashed passwords using libraries like bcrypt.
Creating and validating JWT (JSON Web Token) for user sessions.
Middleware to protect private routes by validating the user's session.
Secure login/logout endpoints to manage session tokens.
Why It's Useful:
This enhances security by adding robust authentication and ensures users can only access their data when authenticated.

Estimated Points: 5
Size Category: Medium

**Comment by edwintran235** [comment]
If the user wants to change their password, will there be any way to implement the change?

**Comment by ssim31** [comment]
This is an important feature to implement and definitely sounds useful.

**Comment by laurensheaa** [comment]
what if the user doesn't remember their password?

**Comment by shubhami77** [comment]
This is key in user security.

**Comment by ShahabKiyani** [comment]
gonna be great for the project!

**Comment by krishsharma1008** [comment]
Here's the updated plan based on your suggestions:

A 'Change Password' feature will be added, requiring the user to provide their current password for verification.
For users who don't remember their password, a 'Forgot Password' flow will be implemented using secure token-based email verification.
Middleware will ensure all sensitive operations, like password changes, are protected with additional validation for security.
These updates will strengthen the authentication system and enhance the user experience. Let me know if there are other features you'd like to see!"
