### ISSUE TITLE
Analytics API for User Insights

### ISSUE THREAD

**Issue by krishsharma1008** [edwintran235/326-team9#60]
Develop a backend API to aggregate data about job applications, including:

Total applications submitted, sorted by status.
Average time to move between application stages (e.g., from "Applied" to "Interviewing").
Insights into the most common application statuses across all users.
Features:

Express.js endpoints for fetching analytics data.
Use SQLite or IndexedDB backend for data querying and aggregation.
API response formatted in JSON for seamless frontend integration.
Why It's Useful:
Provides users with actionable insights into their job application trends and helps them identify areas for improvement.

Estimated Points: 4
Size Category: Medium

**Comment by edwintran235** [comment]
Will the user have access to this data or will it just be for the backend?

**Comment by ssim31** [comment]
This sounds great. Will the analytics API include any filters to make the insights more customizable for users?

**Comment by laurensheaa** [comment]
If the users have access to this data, how will it appear?

**Comment by shubhami77** [comment]
We can then lead the user over to the interview tips page for any tips they might need based on the data.

**Comment by ShahabKiyani** [comment]
looks good

**Comment by krishsharma1008** [comment]
Based on your input:

Users will have access to this data via a dedicated analytics dashboard on the frontend, with visualizations like charts and tables for better understanding.
Filters will be implemented to allow users to customize insights based on status, date range, or application type.
To enhance user engagement, we can integrate a prompt linking them to the interview tips page based on their analytics, as @shubhami77 suggested.
I'll ensure these features are planned into the API and frontend design. Let me know if there's anything else you'd like to add!"

**Comment by krishsharma1008** [comment]
Based on the input:

Users will have access to this data via a dedicated analytics dashboard on the frontend, with visualizations like charts and tables for better understanding.
Filters will be implemented to allow users to customize insights based on status, date range, or application type.
To enhance user engagement, we can integrate a prompt linking them to the interview tips page based on their analytics, as @shubhami77 suggested.
I'll ensure these features are planned into the API and frontend design. Let me know if there's anything else you'd like to add!

**Comment by krishsharma1008** [comment]
Here's the updated plan based on your suggestions:

A 'Change Password' feature will be added, requiring the user to provide their current password for verification.
For users who don't remember their password, a 'Forgot Password' flow will be implemented using secure token-based email verification.
Middleware will ensure all sensitive operations, like password changes, are protected with additional validation for security.
These updates will strengthen the authentication system and enhance the user experience. Let me know if there are other features you'd like to see!"
